### ISSUE TITLE
Error when running DEG

### ISSUE THREAD

**Issue by jamrute** [Coolgenome/iTALK#21]
Hi,

Thanks for creating this great method! I am trying to run DEG for a cell type using:

`deg_Mac<-DEG(subset(data, cell_type=='Macrophages'), method='Wilcox', contrast=c("B","A"))`

where my two compare_groups are "B" and "A" (data$compare_group). However, I get the following error: 

`Error in wilcox.test.formula(counts[i, ] ~ groups) : grouping factor must have exactly 2 levels`

Appreciate any help!

**Comment by eperkan** [comment]
Hi, I encountered a similar problem when I tried to compare two groups. Did you figure out the source of the problem? If so, could you please share your solution?

Thanks!
